# This workflow is necessary to support publishing to GitHub pages as it will push the docs folder to gh-pages.

name: Push mainline changes into gh-pages branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the gh-pages branch
on:
  push:
    branches: [mainline]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_gh-pages_branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build Documents
        run: |
          npm install
          npm run docs
      - name: Push changes
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 
          publish_branch: gh-pages